name: List Dependencies with Licenses

on:
  workflow_dispatch:

# on:
#   pull_request:
#     branches:
#       - trunk

jobs:
  list-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execution permissions for gradlew
        run: chmod +x ./gradlew        

      - name: Gradle Task
        run: |
            ./gradlew tasks

      - name: Generate License Report Info
        run: |
            ./gradlew licenseReport --info

      - name: Generate License Report
        run: |
            ./gradlew clean build licenseReport
